name: Terraform CI/CD

on:
  push:
    branches:
      - dev  # You can change this to your main branch name

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Format Terraform Files
        run: terraform fmt -check

      - name: Plan Terraform Deployment
        run: terraform plan

      # Add more steps here for applying changes, handling state, etc.

        